
package demo.hw.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HelloWorldPortType", targetNamespace = "http://server.hw.demo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldPortType {


    /**
     * 
     * @param text
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:sayHi")
    @WebResult(targetNamespace = "http://server.hw.demo")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://server.hw.demo", className = "demo.hw.server.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://server.hw.demo", className = "demo.hw.server.SayHiResponse")
    public String sayHi(
        @WebParam(name = "text", targetNamespace = "http://server.hw.demo")
        String text);

}
